language: julia

os:
  - osx
  - linux
  - windows
  
julia:
  - 1.4
  
before_script:
    - git clone --depth=1 https://github.com/mathn7/optinum.git mathn7/optinum
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.4
      env:
        - GKSwstype="100"
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs -e 'using Pkg; Pkg.add("Documenter");' --color=yes docs/make.jl
      after_success: skip
